### ISSUE TITLE
Suggestion about deep/shallow copying

### ISSUE THREAD

**Issue by elnazazizi** [UNIVERSE-HPC/course-material#11]
Maybe it would be better to define/describe the meaning of "deep/shallow copy" at first and then give examples for them.

**Comment by elnazazizi** [comment]
In "Recursion" section there are some typos in the code part.

"class Node(object)" should be change to "class Tree(object)" based on the rest of the code.
"self.value" = value should be change to "self.value = name"

**Comment by martinjrobins** [comment]
Thanks @elnazazizi for these, I'll make those changes (or feel free to do a PR)

**Comment by martinjrobins** [comment]
fixed in c6f9e36
