### ISSUE TITLE
Broken cython import on docker training materials

### ISSUE THREAD

**Issue by alexallmont** [UNIVERSE-HPC/course-material#119]
In the 'Take a Guess' solution box on [this page](https://train.oxrse.uk/material/HPCu/technology_and_tooling/docker/creating-container-images), it's failing whilst pip-installing:

      The failure is due to an external management error. Perhaps they've bumped up their safety in a more recent release:
           > [3/3] RUN pip install cython:
          0.558 error: externally-managed-environment
          0.558
          0.558 × This environment is externally managed
          0.558 ╰─>
          0.558     The system-wide python installation should be maintained using the system
          0.558     package manager (apk) only.

This is probably due to one of the packages being updated.

Because cython is not needed on any of the following pages, the simplest way to fix this is to remove reference to it in [creating-container-images.md](https://github.com/UNIVERSE-HPC/course-material/blob/52f557c97525ce5d75b7cc63499e4ef110f0a365/technology_and_tooling/docker/creating-container-images.md?plain=1#L59) in a few places:
- Remove one of the `RUN <INSTALL CMDS FROM SHELL>` lines around line 104.
- Tweak the break-down text around line 112 so it only refers to one run.
- Remove the `RUN pip install cython` from line 152.
- Remove 'and the Cython library' from line 159

However, because the page depends on a supporting docker-intro.zip file, two files in it need to be tweaked:
- basic/Dockerfile
- sum/Dockerfile
Both need line 3 removed, and the zip file updated

**Comment by fcooper8472** [comment]
Decided to resolve by replacing cython with Pandas, which should not have the same permissions issues when installing.

**Comment by alexallmont** [comment]
Unfortunately the pandas change does not fix it, details below, but TL;DR: the quick fix is for now, change the top line `FROM alpine` to `FROM alpine:3.18`. Or if you want to switch this to Ubuntu, use 22.04.

The error is due to a change to the python ecosystem from PEP 668 called [externally managed environments](https://packaging.python.org/en/latest/specifications/externally-managed-environments/#externally-managed-environments) which stops pip from overwriting any system files.

For a more concise summary of the motivation and OSes affected, see [this think](https://pythonspeed.com/articles/externally-managed-environment-pep-668/). It's a good thing, but an annoyance in docker. The solution it recommends is to use virtualenvs, or apt-install python packages that affect the system. The latter works for pytest, but there are no apt packages for numpy or pandas.

The neatest summary on using venvs is here https://pythonspeed.com/articles/activate-virtualenv-dockerfile/, which makes a venv but then the system uses it by default. Then whenever you use python in the container, it's actually the venv version:
    
    ENV VIRTUAL_ENV=/opt/venv
    RUN python3 -m venv $VIRTUAL_ENV
    ENV PATH="$VIRTUAL_ENV/bin:$PATH"

Finally, a lazy but ugly solution is `RUN rm /usr/lib/python*/EXTERNALLY-MANAGED` before pip-installing anything, but this seems like a horrible hack. I would not do this!

**Comment by alexallmont** [comment]
Also if you want to do it per run of pip install you can use `--break-system-packages`

    pip install xyz --break-system-packages

via https://stackoverflow.com/a/76084249
