### ISSUE TITLE
[Revamp] Workflows with Snakemake

### ISSUE THREAD

**Issue by fcooper8472** [UNIVERSE-HPC/course-material#142]
### Links

- [Gutenberg material](https://train.rse.ox.ac.uk/material/HPCu/technology_and_tooling/snakemake)
- [Markdown files](https://github.com/UNIVERSE-HPC/course-material/tree/main/technology_and_tooling/snakemake)

### Areas for improvement

- [x] New release: Snakemake 8, documentation requires updating
  - [x] Minor updates to tutorials (originals located: https://snakemake.readthedocs.io/en/stable/tutorial/tutorial.html and https://snakemake.readthedocs.io/en/stable/tutorial/short.html).
  - [X] Remove mention of atom editor (end-of-life)
  - [X] Fix missing figure (basics, Step 5, bad path)

**Comment by jsbrittain** [comment]
@fcooper8472 happy to take this one if you can assign me to the issue.
