### ISSUE TITLE
Missing learning outcomes in C++ procedural programming

### ISSUE THREAD

**Issue by dc2917** [UNIVERSE-HPC/course-material#160]
The Procedural Programming course under Software Architecture and Design is missing learning outcomes for the C++ chapters.

Learning outcomes are, however, present for the equivalent Python chapters. It should be straight-forward to copy/adapt these over to the C++ material.

**Comment by jcohen02** [comment]
The "arrays" section of the Python procedural programming material is also missing learning outcomes which should ideally be added as part of addressing this issue.
